# Generated by Django 3.2 on 2021-06-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_monitoringformleadsaadhyasolution_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABHMonForm',
        ),
        migrations.DeleteModel(
            name='AdityaBirlaMonForm',
        ),
        migrations.DeleteModel(
            name='BagyalakshmiMonForm',
        ),
        migrations.DeleteModel(
            name='DanialWellingtonInboundMonForm',
        ),
        migrations.DeleteModel(
            name='DigitalSwissMonForm',
        ),
        migrations.DeleteModel(
            name='HealthyPlusMonForm',
        ),
        migrations.AddField(
            model_name='accutimemonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='camindustrialmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='citizencapitalmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='embassyluxurymonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='glydeappmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='goldeneastmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='ibizmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='iibmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='jjstudiomonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='kalkifashions',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='microdistributingmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='millenniumscientificmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadsadvanceconsultants',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadsallenconsulting',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadscitysecurity',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadscts',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadsgetarates',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadsinfothinkllc',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadsinsalvage',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadslouisville',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadsmedicare',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadspsecu',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadssystem4',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadstentamusfood',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadstentamuspet',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='mtcosmeticsmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='navigatorbiomonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='optimalstudentloanmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='protostarmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='qbiqmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurentsolmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='ritbrainmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='roofwellmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='scalamonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='solarcampaignmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='standspotmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='terraceoleadmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='upfrontonlinellcmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='wtumonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='yeshealthmolinamonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
        migrations.AddField(
            model_name='zerostressmarketingmonform',
            name='type',
            field=models.CharField(default='Outbound', max_length=50),
        ),
    ]
