# Generated by Django 3.2 on 2021-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20210617_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='campaign_id',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='qa_id',
        ),
        migrations.AddField(
            model_name='campaigns',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
