# Generated by Django 3.2.4 on 2021-06-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_sterlingstrategiesoutboundmonform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FameHouseMonitoringForm',
        ),
        migrations.DeleteModel(
            name='InboundMonitoringFormNucleusMedia',
        ),
        migrations.DeleteModel(
            name='MasterMonitoringFormGetaRatesPSECU',
        ),
    ]
