# Generated by Django 3.2.4 on 2021-06-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20210617_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TonCoaInboundMonForms',
        ),
        migrations.AddField(
            model_name='mastermonitoringformtonncoainboundcalls',
            name='type',
            field=models.CharField(default='Inbound', max_length=50),
        ),
        migrations.AlterField(
            model_name='mastermonitoringformtonncoainboundcalls',
            name='process',
            field=models.CharField(default='Tonn Coa Inbound', max_length=50),
        ),
    ]
