# Generated by Django 3.2.4 on 2021-06-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20210618_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrinterPixMonForm',
        ),
        migrations.AddField(
            model_name='printerpixmastermonitoringforminboundcalls',
            name='type',
            field=models.CharField(default='Inbound', max_length=50),
        ),
    ]
