# Generated by Django 3.2.4 on 2021-06-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_auto_20210618_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='superplaymonform',
            name='type',
            field=models.CharField(default='Email - Chat', max_length=50),
        ),
    ]
