# Generated by Django 3.2.4 on 2021-06-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_auto_20210621_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraceochatemailmonform',
            name='type',
            field=models.CharField(default='Email - Chat', max_length=50),
        ),
    ]
