# Generated by Django 3.2.4 on 2021-06-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_auto_20210625_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerpixmastermonitoringformchatsemail',
            name='type',
            field=models.CharField(default='Email - Chat', max_length=50),
        ),
    ]
