# Generated by Django 3.2.4 on 2021-06-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_printerpixmastermonitoringformchatsemail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='practomonform',
            name='type',
            field=models.CharField(default='Email - Chat', max_length=50),
        ),
    ]
