# Generated by Django 3.2.4 on 2021-06-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_furbabymonform_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='akdyemailmonform',
            name='type',
            field=models.CharField(default='Email - Chat', max_length=50),
        ),
    ]
