# Generated by Django 3.2.4 on 2021-06-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_digitalswissgoldemailchatmonform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlutoManagementMonForm',
        ),
        migrations.AddField(
            model_name='flamonitoringform',
            name='type',
            field=models.CharField(default='FLA', max_length=50),
        ),
    ]
