# Generated by Django 3.2.4 on 2021-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_auto_20210625_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmonitoringformeva',
            name='type',
            field=models.CharField(default='Email/Chat Other', max_length=50),
        ),
        migrations.AddField(
            model_name='chatmonitoringformpodfather',
            name='type',
            field=models.CharField(default='Email/Chat Other', max_length=50),
        ),
    ]
