# Generated by Django 3.2.4 on 2021-06-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_auto_20210625_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerpixmastermonitoringformchatsemail',
            name='process_new',
            field=models.CharField(default='Printer Pix Chat Email', max_length=50),
        ),
    ]
