from django.contrib import admin

from .models import *


class CampaignSearch(admin.ModelAdmin):
    search_fields = ('name','type')
    list_display = ('name','type')

admin.site.register(Team)
admin.site.register(Profile)
admin.site.register(Process)
admin.site.register(Empdata)
admin.site.register(Campaigns,CampaignSearch)
admin.site.register(ProfileCreatedByManagers)
admin.site.register(PractoWithSubCategory)

admin.site.register(ProfileNewtoAddUserandProfile)

# Monitoring Forms

admin.site.register(ChatMonitoringFormEva)     # view done
admin.site.register(ChatMonitoringFormPodFather)     # view done
admin.site.register(FameHouseNewMonForm)
admin.site.register(FLAMonitoringForm)     # view done
admin.site.register(MTCosmeticsMonForm)      # view done
admin.site.register(MasterMonitoringFormTonnCoaInboundCalls)
admin.site.register(MonitoringFormLeadsAadhyaSolution)
admin.site.register(PrinterPixMasterMonitoringFormInboundCalls)
admin.site.register(PrinterPixMasterMonitoringFormChatsEmail)
admin.site.register(MonitoringFormLeadsInsalvage)
admin.site.register(MonitoringFormLeadsMedicare)
admin.site.register(MonitoringFormLeadsCTS)
admin.site.register(MonitoringFormLeadsTentamusFood)
admin.site.register(MonitoringFormLeadsTentamusPet)
admin.site.register(MonitoringFormLeadsCitySecurity)
admin.site.register(MonitoringFormLeadsAllenConsulting)
admin.site.register(MonitoringFormLeadsSystem4)
admin.site.register(MonitoringFormLeadsLouisville)
admin.site.register(MonitoringFormLeadsInfothinkLLC)
admin.site.register(MonitoringFormLeadsPSECU)
admin.site.register(MonitoringFormLeadsGetARates)
admin.site.register(MonitoringFormLeadsAdvanceConsultants)
admin.site.register(FurBabyMonForm)
admin.site.register(UpfrontOnlineLLCMonform)
admin.site.register(MicroDistributingMonForm)
admin.site.register(JJStudioMonForm)
admin.site.register(ZeroStressMarketingMonForm)
admin.site.register(WTUMonForm)
admin.site.register(RoofWellMonForm)
admin.site.register(GlydeAppMonForm)
admin.site.register(MillenniumScientificMonForm)
admin.site.register(StandSpotMonForm)
admin.site.register(CamIndustrialMonForm)
admin.site.register(OptimalStudentLoanMonForm)
admin.site.register(NavigatorBioMonForm)
admin.site.register(AKDYEmailMonForm)
admin.site.register(IbizMonForm)
admin.site.register(DanielWellinChatEmailMonForm)
admin.site.register(ProtostarMonForm)
admin.site.register(ABHindalcoInboundMonForm)
admin.site.register(AmerisaveEmailMonForm)
admin.site.register(DanielWellingtonOutboundMonForm)
admin.site.register(DigitalSwissGoldOutboundMonForm)
admin.site.register(EmbassyLuxuryMonForm)
admin.site.register(IIBMonForm)
admin.site.register(TerraceoLeadMonForm)
admin.site.register(TerraceoChatEmailMonForm)
admin.site.register(KalkiFashions)
admin.site.register(SuperPlayMonForm)
admin.site.register(PractoMonForm)
admin.site.register(ScalaMonForm)
admin.site.register(GoldenEastMonForm)
admin.site.register(CitizenCapitalMonForm)
admin.site.register(RitBrainMonForm)
admin.site.register(RestaurentSolMonForm)
admin.site.register(QBIQMonForm)
admin.site.register(AccutimeMonForm)
admin.site.register(latest)
admin.site.register(HiveIncubatorsOutboundMonForm)
admin.site.register(IEDHHInboundMonForm)
admin.site.register(Ri8BrainEmailMonForm)
admin.site.register(QuickAutoPartsOutboundMonForm)
admin.site.register(PractoNewVersion)
admin.site.register(GubagooAuditForm)
admin.site.register(CleanLivingHealthWellnessOutboundMonForm)
admin.site.register(PractoOutboundMonForm)
admin.site.register(LJHubInboundMonForms)
admin.site.register(ILMakiageEmailChatForm)
admin.site.register(DigitalSwissGoldEmailChatMonForm)
admin.site.register(DawnFinancialOutbound)
admin.site.register(WinopolyOutbound)
admin.site.register(MonitoringFormMobile22InboundCalls)
admin.site.register(XportDigitalOutbound)
admin.site.register(XportDigitalInboundMonForm)
admin.site.register(ABHindalcoMonForm)
admin.site.register(CalistaOutboundMonForm)
admin.site.register(GlobalArkOutboundMonform)
admin.site.register(DIDevelopOutbound)
admin.site.register(FreeholdOutboundMonForm)
admin.site.register(ZeamoOutboundMonForm)
admin.site.register(SapphireMedicalsOutboundMonForm)
admin.site.register(EehhaaaOutboundMonForm)
admin.site.register(CalistaInboundMonForm)
admin.site.register(GlobalArkInboundMonForm)
admin.site.register(AllCarePhysicalTherapyMonform)
admin.site.register(ExecutiveCapitalResourcesmonform)
admin.site.register(BrightWayOutboundmonform)
admin.site.register(BuildinglabLLCOutboundmonform)
admin.site.register(BlazingHogEmailChatmonform)
admin.site.register(HardHatTechnologiesInboundMonForm)
admin.site.register(ThirdWaveInboundMonForm)
admin.site.register(HardHatTechnologiesOutboundmonform)
admin.site.register(GretnaMedicalCenterInboundMonForm)
admin.site.register(ThirdWaveOutboundmonform)
admin.site.register(GlobalPharmaOutboundmonform)
admin.site.register(RedefinePlasticsOutboundmonform)
admin.site.register(K7Outboundmonform)
admin.site.register(TrialMappingOutboundmonform)
admin.site.register(GretnaMedicalCenterEmailChatForm)
admin.site.register(EduClassOutboundmonform)
admin.site.register(CredAvenueOutboundmonform)




